services:
  db:
    image: postgres:16
    container_name: socialnetwork-db
    environment:
      POSTGRES_DB: socialnetwork
      POSTGRES_USER: social
      POSTGRES_PASSWORD: socialpw
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
